### ISSUE TITLE
Incorrectly generated schema for subclasses

### ISSUE THREAD

**Issue by martinpetlus** [epiphone/class-validator-jsonschema#104]
Hi @epiphone :),

thank you for all your work on this project. I have been using this project successfully for quite some time, but recently we have noticed some behavior that we think is a bug. Consider the code below:

```ts
import { IsOptional, IsString, MaxLength } from "class-validator";
import { targetConstructorToSchema } from "class-validator-jsonschema";

class Post {
  @IsString() id!: string;
}

class BlogPost extends Post {
  @IsOptional()
  @MaxLength(20, { each: true })
  tags?: string[];
}

class JournalPost extends BlogPost {}

const schema = targetConstructorToSchema(JournalPost);
console.log(JSON.stringify(schema, null, 2));
```

I would expect that the `console.log` logs the following schema (same as for `BlogPost`):

```json
{
  "properties": {
    "tags": {
      "items": {
        "maxLength": 20,
        "type": "string"
      },
      "type": "array"
    },
    "id": {
      "type": "string"
    }
  },
  "type": "object",
  "required": [
    "id"
  ]
}
```

But instead, it logs this schema:

```json
{
  "properties": {
    "id": {
      "type": "string"
    }
  },
  "type": "object",
  "required": [
    "id"
  ]
}
```

It looks like the metadata for the `BlogPost` class is not considered during schema generation. This behavior produces incorrect OpenAPI schemas in our application. Is this expected behavior or is it a bug?

By the way, validations using `JournalPost` are working correctly.

Thank you.

**Comment by kclay** [comment]
@epiphone any chance of getting the linked PR merged in? Running into this issue as well

**Comment by epiphone** [comment]
Released in https://github.com/epiphone/class-validator-jsonschema/releases/tag/v5.0.1. Thank you for the contribution!
