### ISSUE TITLE
Locked version of class-validator and class-transformer out of date

### ISSUE THREAD

**Issue by arvinsingla** [epiphone/class-validator-jsonschema#11]
Hey thanks for the great work on this project!

I ran into an issue using this library in my NestJS project due to a version miss-match in the `class-transformer` library. My base project was using the latest minor version `0.2.3` and this project is locked to the previous minor version `0.1.9`. Because of this I couldn't pass the `defaultMetadataStorage` to the `validationMetadatasToSchemas` method because the instances were different.

I've currently downgraded my project to use the `0.1.9` version which is working but it would be great if we could either remove the lock file (always pull latest based on package.json rules) or update the lock to use the latest versions.

**Comment by epiphone** [comment]
Hi, I updated the deps in `v1.2.1`. If this keeps happening let's look into relaxing the lock file like you mentioned. Thanks!

**Comment by michaelneu** [comment]
I'm running into this as well now, especially as the version on NPM appears to not be the one with the updated dependencies (`yarn info class-validator-jsonschema` yields `class-validator@^0.7.3` and `class-transformer@^0.1.9`).

Could you maybe use both `class-transformer` and `class-validator` as `peerDependencies`? Having a specific version might cause trouble for more users, as `routing-controllers` has its own issues with version mismatches (e.g. see [here](https://github.com/typestack/routing-controllers/issues/384)).

**Comment by epiphone** [comment]
@michaelneu the two libs are now peer dependencies as of `1.3.0`. Thanks for pointing me in the right direction!
