### ISSUE TITLE
Generate from a specific Class 

### ISSUE THREAD

**Issue by zgababa** [epiphone/class-validator-jsonschema#15]
Hello, 

The generation works fine, but I would like to generate from a specific class.

```
// blogPost.ts
class Foo {
  @IsString() id: string
}

export class BlogPost {
  @ValidateNested()
  @Type(() => Foo)
  foo: Foo
}

const metadatas = (getFromContainer(MetadataStorage) as any).validationMetadatas
const schemas2 = validationMetadatasToSchemas(metadatas, {
  classTransformerMetadataStorage: defaultMetadataStorage,
}) // => Works well
```

```
import {BlogPost} from './blogPost'
const jsonSchema  = generateJSONSchema(BlogPost); // Is it possible to generate a schema with a class passed in params ? 
```

Thank you

**Comment by epiphone** [comment]
Don't think so I'm afraid, no. `class-validator` doesn't store any validation information in `BlogPost` class itself but in a separate `MetadataStorage` object instead ([like so](https://github.com/typestack/class-validator/blob/c2acfa4aba2f723693ac479826fb19b6a533e547/src/metadata/MetadataStorage.ts#L37)).
