### ISSUE TITLE
Not Cross-platform package, only for MacOS (not working on Ubuntu etc)

### ISSUE THREAD

**Issue by 99ACA** [epiphone/class-validator-jsonschema#16]
The current package working only on MacOS, is used fsevents (Native access to MacOS FSEvents in Node.js).
Is there a workaround?

**Comment by 99ACA** [comment]
![image](https://user-images.githubusercontent.com/29768832/60833288-97917680-a1c6-11e9-8413-9e540804d7f1.png)

**Comment by 99ACA** [comment]
The current code sample doesn't work - 
import {
  getFromContainer,
  IsDefined,
  IsEmail,
  IsOptional,
  IsString,
  MaxLength,
  MetadataStorage,
  ValidateNested} from 'class-validator'
import * as _ from 'lodash'
import { validationMetadatasToSchemas, JSONSchema } from 'class-validator-jsonschema';

class User {
  @IsDefined()
  @IsString()
  id: string

  @IsEmail() email: string

  @IsOptional()
  @MaxLength(20, { each: true })
  tags: string[]
}

// @ts-ignore: not referenced
class Post {
  @IsOptional()
  @ValidateNested()
  user: User
}

const metadata = _.get(getFromContainer(MetadataStorage), 'validationMetadatas')
const defaultSchemas = validationMetadatasToSchemas(metadata);

console.log(defaultSchemas);


The result is - 
{ User:
   { properties: { id: {}, email: [Object], tags: [Object] },
     type: 'object',
     required: [ 'id', 'email' ] },
  Post: { properties: { user: [Object] }, type: 'object' } }

**Comment by epiphone** [comment]
`fsevents` is an optional dependency and ignored in linux, you're good to go!
