### ISSUE TITLE
Array of object not working for routing-controllers-openapi 

### ISSUE THREAD

**Issue by Brian-NgH777** [epiphone/class-validator-jsonschema#18]
Hi I use **routing-controllers-openapi, routing-controllers, class-validator, class-validator-jsonschema and class-validator** to make swagger

This is my Array of object is declared

export default class UserInformation{
  @IsString()
  name: string

  @IsString()
  code: string
}

export default class User {
    @IsString()
    email: string

    @IsString()
    pass: string

    @ValidateNested()
    user: UserInformation

    @ValidateNested({ each: true })
    @Type(() => UserInformation)
    users: UserInformation[]
}

Users (user3s) not working. It is always equal to null
![image](https://user-images.githubusercontent.com/53888210/62881629-66264080-bd5a-11e9-9eb1-39fb154f197a.png)

I use **swagger-ui-express** to create swagger pages
Could you help me.
Thank

**Comment by epiphone** [comment]
Follow the instructions here: https://github.com/epiphone/class-validator-jsonschema#validatenested-and-arrays

**Comment by KolCrooks** [comment]
@epiphone I am also having a problem with generation when it comes to Class arrays. 
```Typescript
export class CoursePropsSchema {
  /** course id */
  @IsString() id!: string;
  /** course name */
  @IsString() name!: string;
  /** list of students */
  @ValidateNested({each: true})
  @Type(() => StudentPropsSchema)
  students!: StudentPropsSchema[];
  /** list of assignments */
  @ValidateNested({each: true})
  @Type(() => AssignmentPropsSchema)
  assignments!: AssignmentPropsSchema[];
  /** list of course owners */
  @ValidateNested({each: true})
  @Type(() => UserPropsSchema)
  owners!: UserPropsSchema[];
}
```
generates to
```JSON
      "CoursePropsSchema": {
        "properties": {
          "id": {"type": "string"},
          "name": {"type": "string"},
          "students": {"$ref": "#/components/schemas/Array"},
          "assignments": {"$ref": "#/components/schemas/Array"},
          "owners": {"$ref": "#/components/schemas/Array"}
        },
        "type": "object",
        "required": ["id", "name", "students", "assignments", "owners"]
      },
```

even when I followed the instructions with
validationMetadatasToSchemas({
      refPointerPrefix: '#/components/schemas/', // This part is from routing-controllers-openapi's instructions
      classTransformerMetadataStorage: defaultMetadataStorage,
})
I don't know why this could be happening. It might be a problem with `routing-controllers-openapi` but the CoursePropsSchema schema is generated by the `validationMetadatasToSchemas()` method.

Another idea that I have about the potential problem is something with ` refPointerPrefix: '#/components/schemas/',` Maybe it is causing some problems somewhere? It is the only thing different from the instructions. That and the order that I imported / used `@Type` and everything.

**Comment by Alko89** [comment]
@epiphone I followed the instructions but still get items as string array:

![image](https://user-images.githubusercontent.com/2822030/154263963-2babb49f-95d9-47e1-b273-06c0aa4e12b5.png)

![image](https://user-images.githubusercontent.com/2822030/154263921-a01b0cfd-046b-4ed8-9bea-a3273a666757.png)

**Comment by ilia-shakalov** [comment]
@alko89 @Brian-NgH777 not sure if it is still relevant to you, but for people who also faces this issue, you can decorate your property with following decorator:
```typescript
import { JSONSchema } from 'class-validator-jsonschema';

export function FixArrayJsonSchemaReference(reference: any): PropertyDecorator {
    return JSONSchema({
        $ref: `#/components/schemas/${reference.name}`,
    });
}
``` 

```typescript
export class SomeArrayResponseDto {
    @ValidateNested({ each: true })
    @Type(() => SomeDto)
    @FixArrayJsonSchemaReference(SomeDto)
    readonly rows: SomeDto[];
}
```
that will fix $ref from `Array` to `SomeDto`.

@epiphone, obviously, reference is taken from the type of field, not from what `@Type` decorator implies, as docs mentioned by you says

**Comment by ilia-shakalov** [comment]
@alko89 @Brian-NgH777 not sure if it is still relevant to you, but for people who also faces this issue, you can decorate your property with following decorator:
```typescript
import { JSONSchema } from 'class-validator-jsonschema';

export function FixArrayJsonSchemaReference(reference: any): PropertyDecorator {
    return JSONSchema({
        items: {
            $ref: `#/components/schemas/${reference.name}`,
        },
    });
}
``` 

```typescript
export class SomeArrayResponseDto {
    @ValidateNested({ each: true })
    @Type(() => SomeDto)
    @FixArrayJsonSchemaReference(SomeDto)
    readonly rows: SomeDto[];
}
```
that will fix $ref from `Array` to `SomeDto`.

@epiphone, obviously, reference is taken from the type of field, not from what `@Type` decorator implies, as docs mentioned by you says
