### ISSUE TITLE
Enum keys are used instead of values

### ISSUE THREAD

**Issue by DimaIT** [epiphone/class-validator-jsonschema#23]
Enum is given:
```typescript
enum Test {
  A = 'aaa',
  B = 'bbb',
}
```
And validated class:
```typescript
class TestClass {
  @IsEnum(Test)
  type: Test;
}
```
Result json schema:
```json
        "TestClass": {
          "properties": {
            "type": {
              "enum": [
                "A",
                "B"
              ],
              "type": "string"
            }
          },
          "type": "object",
          "required": [
            "type"
          ]
        },
```
I suppose in result schema enum values should be used, but not keys. However I'm not 100% sure about all cases.

If my assumption is correct, then it can be fixed by changing `Object.keys` to `Object.values` here:
https://github.com/epiphone/class-validator-jsonschema/blob/b7bd8beb23f4f868079a7fcf7adee9e856a2bcbb/src/defaultConverters.ts#L115

**Comment by epiphone** [comment]
You're 100% right, good catch! Published a fix in `v1.3.1`.
