### ISSUE TITLE
Support for class-transformer?

### ISSUE THREAD

**Issue by JamesMcFall** [epiphone/class-validator-jsonschema#30]
Hey @epiphone,
Thanks for this package, and for [routing-controllers-openapi](https://github.com/epiphone/routing-controllers-openapi) - it's going to save a huge amount of man-hours on the various TS based API's I'm working on at the moment.

Because I'm using [Class Transformer](https://github.com/typestack/class-transformer) as well as [Routing Controllers](https://github.com/typestack/routing-controllers) (with TypeORM and class validator), the models that are being used for the schemas are showing the model property names - however the I need it to show the transformed names.

```
export class MyCoolModel 
{
    @IsString()
    @Expose({name: `what_a_cool_field`})
    @Column({unique: true, type: `text`, nullable: false})
    public abstract whatACoolField: string;
}
```

And obviously in the schema it's showing:

```
"schemas": {
    "MyCoolModel": {
        "properties": {
            "whatACoolField": {
                "type": "string",
                "minLength": 1
              },
... etc ...
```

However I'm wanting it to show the "what_a_cool_field" name.

**Are there any plans to roll class-transformer support into this library?**

Have you got any advice on how to approach this? (I was thinking of having to parsing the class-validator metadata (easy) and swap out the field names from the class-transformer metadata (which I'm having issues with).

Thanks again.

**Comment by epiphone** [comment]
Hi James, glad to hear it!

I don't have any plans to extend the library myself, no. This looks like a totally valid use case that the library should support, however, and I'm happy to merge a PR if you find the time to cobble something together.

We already have a config option to pass in the default class-transformer storage object (used [here](https://github.com/epiphone/class-validator-jsonschema/blob/02fdbaa4d14c34af320452c9e9821365beffcd1e/src/defaultConverters.ts#L28)), so I'd start with that and the storage object's [`findExposeMetadata` method](https://github.com/typestack/class-transformer/blob/develop/src/metadata/MetadataStorage.ts#L84). Specifically I imagine we'll need to iterate through [this `properties` object's](https://github.com/epiphone/class-validator-jsonschema/blob/02fdbaa4d14c34af320452c9e9821365beffcd1e/src/index.ts#L33) keys, check for associated expose metadata and rename the key if necessary.

**Comment by JamesMcFall** [comment]
Hey Aleksi.
I'm unlikely have the time at least in the near future to try to help get this into this package, so I will close the issue, but should anyone else come across this, below is how I managed to get it working on the project I'm working on.

I already have the model metadata (which is the ValidationMetadata from TypeORM). This method iterates over it, finds the corresponding metadata for that property in the Class Transformer metadata, and then if it gets a property name match, it updates the name and saves it to a new array. Items are excluded if they aren't found in Class Transformer (i.e. no @Expose decorator).

I'm sure there are better ways to do it, but this got me where I need to be.

```
import { defaultMetadataStorage as CTMetadataStorage } from 'class-transformer/storage';
...

    private _fixNamesAndFilterModelMeta(modelMetadata: ValidationMetadata[]): ValidationMetadata[]
    {
        const filteredMetadata: ValidationMetadata[] = [];

        // eslint-disable-next-line @typescript-eslint/no-explicit-any
        modelMetadata.forEach((metadataRow: ValidationMetadata) => 
        {

            const fieldToFind: string = metadataRow.propertyName;
            
            // Look up class transformer metadata for model
            // eslint-disable-next-line @typescript-eslint/no-explicit-any
            const ctMetadata = CTMetadataStorage.getExposedMetadatas(metadataRow.target as any);

            const ctMetaForField = ctMetadata.filter((ctMetaRow: ExposeMetadata) => 
                ctMetaRow.propertyName == fieldToFind);

            // If we've found class transformer metadata, amend the property name and save to the filtered metadata
            if (ctMetaForField.length) 
            {
                metadataRow.propertyName = ctMetaForField[0].options.name ?? metadataRow.propertyName;
                filteredMetadata.push(metadataRow);
            } 
        });

        return filteredMetadata;

    }
```

If someone stumbles on this and it's not clear enough, ping me and I'm happy to provide more detail.

Thanks again for the package Aleksi.

**Comment by epiphone** [comment]
`@Expose` is now handled in https://github.com/epiphone/class-validator-jsonschema/releases/tag/v5.1.0.
