### ISSUE TITLE
[suggestion] Suggestion for readme

### ISSUE THREAD

**Issue by kalani96746** [epiphone/class-validator-jsonschema#33]
I gave up trying to use your library because it didnʻt work.  (angular land) ...then I realized 5 hours later that I needed to do this instead:

		const metadatas = (getMetadataStorage() as any).validationMetadatas;
		const constraintMetadatas = (getMetadataStorage() as any).constraintMetadatas;
		const schemas = validationMetadatasToSchemas(metadatas)

..which did work..maybe add this to your readme @epiphone? 

PS - excellent job with this!

**Comment by epiphone** [comment]
Just released v2.0.0 with a hopefully more sensible API. Thanks for the suggestion!
