### ISSUE TITLE
additionalProperties has incorrect type of array

### ISSUE THREAD

**Issue by andrew-ignatiev** [epiphone/class-validator-jsonschema#4]
Hey,

First of all many thanks for your great work. I spotted that additionalProperties has incorrect type of array and as a result transforms to incorrect openapi output. According to latest specification https://swagger.io/specification/#schemaObject 

> additionalProperties - Value can be boolean or object. Inline or referenced schema MUST be of a Schema Object and not a standard JSON Schema.

Is it possible to fix it?

**Comment by epiphone** [comment]
Hi Andrew,

I updated the `openapi3-ts` dependency in version `1.1.3` which should take care of this. Thanks for the heads-up!
