### ISSUE TITLE
Empty required fields

### ISSUE THREAD

**Issue by andrew-ignatiev** [epiphone/class-validator-jsonschema#5]
Hey Aleksi,

Another one issue which I spotted is that empty required fields in schema produce  not valid output `required: []`

Error messages from different validators are:

**https://editor.swagger.io/**
> Schema error at components.schemas['Test'].required
> should NOT have less than 1 items
> limit: 1

**https://mermade.org.uk/openapi-converter**
> status: false
> message: 'expected Array [] not to be empty (false negative fail)'
> context: '#/components/schemas/Test'

Can it be fixed as well?

**Comment by epiphone** [comment]
Pushed a fix in `1.1.3`. Thanks!
