### ISSUE TITLE
Anyway to exclude some decorators

### ISSUE THREAD

**Issue by saachinsiva** [epiphone/class-validator-jsonschema#50]
Hello 

First of all I would like to thank you for this wonderful module. I am very new to class-validator module itself and just started using it in one of our projects and really liked it. I was able to add this module to generate schema from our nestjs project however some of the models we have contain some extra properties that's been used only internally and I am wondering is there anyway to exclude those properties from being added to the schema. E.g if any property is decorated with @Exclude , can be hidden from the schema file.

Thank you.

**Comment by epiphone** [comment]
Published handling for Exclude decorator in https://github.com/epiphone/class-validator-jsonschema/releases/tag/v2.1.0.

`Expose` decorator is not supported yet. PRs are welcome!
