### ISSUE TITLE
Remove lodash dependency

### ISSUE THREAD

**Issue by epiphone** [epiphone/class-validator-jsonschema#52]
Replace lodash function calls with native Javascript code.

**Comment by mikeguta** [comment]
Hi @epiphone 
I have a PR for this by way of introduction. Not sure what the contribution guidelines are, I just tried to keep with the existing style.

**Comment by epiphone** [comment]
Awesome! I'll review it during the weekend.

**Comment by epiphone** [comment]
Released in https://github.com/epiphone/class-validator-jsonschema/releases/tag/v3.0.1
