### ISSUE TITLE
Cannot find module 'class-transformer/metadata/MetadataStorage'

### ISSUE THREAD

**Issue by angyRincon** [epiphone/class-validator-jsonschema#57]
![image](https://user-images.githubusercontent.com/54361894/105616725-f9183680-5da6-11eb-8dbc-9a7bbf6defd1.png)

The actual route is this one
![image](https://user-images.githubusercontent.com/54361894/105616746-2664e480-5da7-11eb-829d-c375e635da3d.png)

But It uses this one 
![image](https://user-images.githubusercontent.com/54361894/105616769-3b417800-5da7-11eb-92d1-96dc38771efa.png)

Thanks!!

**Comment by epiphone** [comment]
You need to downgrade to `class-transfomer@v0.3.1`. This library is currently incompatible with `class-transformer@0.3.2`, see https://github.com/epiphone/class-validator-jsonschema/pull/56.
