### ISSUE TITLE
Issue with routing-controllers-openapi

### ISSUE THREAD

**Issue by andrew-ignatiev** [epiphone/class-validator-jsonschema#6]
Hey Aleksi,

Thank you for your quick update. But seems the recent update of dependency now cause issue with type of generated schemas which is not assignable to `additionalProperties: Partial<OpenAPIObject>` in `routing-controllers-openapi` . 

```javascript
const metadatas = (getFromContainer(MetadataStorage) as any).validationMetadatas;
const schemas = validationMetadatasToSchemas(metadatas, {
  refPointerPrefix: '#/components/schemas/',
});

// Parse routing-controllers classes into OpenAPI spec:
const storage = getMetadataArgsStorage();
const spec = routingControllersToSpec(storage, routingControllersOptions, {
  components: { schemas }
});
```

The code above now generates outputs with error:

> error TS2345: Argument of type '{ components: { schemas: { [key: string]: SchemaObject; }; }; }' is not assignable to parameter of type 'Partial<OpenAPIObject>'.
> Types of property 'components' are incompatible.
> Type '{ schemas: { [key: string]: SchemaObject; }; }' is not assignable to type 'ComponentsObject'.
> Types of property 'schemas' are incompatible.
> Type '{ [key: string]: SchemaObject; }' is not assignable to type '{ [schema: string]:SchemaObject; }'.

Could you check please?

**Comment by epiphone** [comment]
Right, I forgot to bump up `openapi3-ts` in `routing-controllers-openapi` too. Pushed a fix now. Good catch!
