### ISSUE TITLE
Regular expression for IS_DATE_STRING is missing escape characters

### ISSUE THREAD

**Issue by mcheale-parkit** [epiphone/class-validator-jsonschema#68]
When using the `@IsDateString()` decorator I would get the error:

`err: "Validation error: data.startTime should match pattern \"d{4}-[01]d-[0-3]dT[0-2]d:[0-5]d:[0-5]d.d+Z?\""`

When passing a date value of:

`"2021-05-01T12:00:00.000Z"`

Due to the regular expression expecting the character 'd' and not a digit.

**Comment by epiphone** [comment]
Released your fix in https://github.com/epiphone/class-validator-jsonschema/releases/tag/v3.0.2, thanks!

The regular expression is still all sorts of wonky but this is in the right direction.
