### ISSUE TITLE
Bug with decorator `@Exclude` processing on classes inheritance

### ISSUE THREAD

**Issue by scarych** [epiphone/class-validator-jsonschema#77]
Hello.
I've found some serious problem with `@Exclude` decorator processing on filtering metadata with `isExcluded` when I trying to overload some properties on classes inheritance.

Trying to explain on code sample:
```ts
// create some basic class
class UserProfile {
  @IsString()
  name: string;

  @IsString()
  surname: string;

  @IsDate()
  birthDate: Date;
}

// declare class with overloaded `birthDate` 
class UserProfileSkipDate extends UserProfile {
  @Exclude()
  @IsOptional()
  birthDate: Date;
}
```

But after creating JSONSchema for `UserProfileSkipDate` I see that data:
```json
{
   "properties":{
      "name":{
         "type":"string"
      },
      "surname":{
         "type":"string"
      },
      "birthDate":{
         "oneOf":[
            {
               "format":"date",
               "type":"string"
            },
            {
               "format":"date-time",
               "type":"string"
            }
         ]
      }
   },
   "type":"object",
   "required":[
      "name",
      "surname",
      "birthDate"
   ]
}
```

You may see, that the resulting JSON still contains the `birthDate` attributes into `properties` and `required`. 

That happens because filter for `metas` value into function `validationMetadataArrayToSchemas` detect `IsExclude` on the top of list and correctly ignores `birthDate` meta the first iteration, but on the next steps still keeps metadata from `getInheritedMetadatas` list and in fact restores the default metadata for overloaded property.

I've prepared the PR to fix this bug. Hope you'll approve that.

**Comment by epiphone** [comment]
Published in https://github.com/epiphone/class-validator-jsonschema/releases/tag/v3.1.1. Thank you for the contribution!
